remote_theme: marella/jekyll-theme-documentation
#remote_theme: pawamoy/jekyll-readthedocs

#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

permalink: pretty
nav:
  - Welcome and Background:
    - Welcome: ''
  - Intro to Tapis and The Command Line Interface:
    - Intro to Tapis(Agave): block1/tapis-intro
    - Intro to Tapis CLI: block1/tapis-cli
  - Tapis Systems:
    - Intro to Tapis Systems: block1/tapis-systems
  - Tapis Apps:
    - Intro to Tapis Apps: block2/apps
  - Tapis Jobs:
    - Intro to Tapis Jobs with Aloe: block2/jobs


theme: jekyll-theme-hacker